### ISSUE TITLE
Add tutorials using `yaml` configure file.

### ISSUE THREAD

**Issue by yingxingcheng** [yingxingcheng/horton-part#12]
An much easier way to run the code is using a `yaml` file.

For example, run `part-dens` to do `LISA-SC` calculations for `C2H2` and `C2H4` molecules when density has been generated by `part-gen`.

```yaml
part-dens:
  inputs:
  - ../../dens/C2H2_LDA.npz
  - ../../dens/C2H4_LDA.npz
  outputs:
  - output/part_C2H2_LDA.npz
  - output/part_C2H4_LDA.npz
  log_files:
  - output/C2H2_LDA.log
  - output/C2H4_LDA.log
  type: lisa
  maxiter: 100000
  threshold: 1.0e-08
  lmax: 3
  radius_cutoff: .inf
  log_level: INFO
  inner_threshold: 1.0e-12
  basis_func: gauss
  func_file: null
  solver: sc

```
